### ISSUE TITLE
Book of Summoner can give duplicate abilities

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#490]
It should not give an ability the player already has. Should only give abilities the player does not have. 
![image](https://user-images.githubusercontent.com/16277198/99415024-82486280-294b-11eb-84c5-5100957fb2b3.png)

It can also cause bugs like this:
![image](https://user-images.githubusercontent.com/16277198/99415122-9ab87d00-294b-11eb-8e5a-e2bded308725.png)

![image](https://user-images.githubusercontent.com/16277198/99415096-942a0580-294b-11eb-8c59-842e42af33d3.png)

**Comment by HappyFeedFriends** [comment]
fixed in next patch

**Comment by darklordabc** [comment]
Not fixed

**Comment by fcalife** [comment]
Circumvented in https://github.com/dota2unofficial/custom_hero_clash/commit/02254a2cd24ebcb31a2d29b29ab16c3948c2ffa7 by giving summoner book a forced 10 seconds cooldown.

This gives the hero builder time to properly remove the abilities involved (the bug was happening because abilities already removed, but still not deleted, were being rolled again). It's a safer alternative than skipping the 10 second delay for summon abilities.
